# Generated by Django 6.0 on 2026-01-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_favouritecocktail_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CocktailViews',
        ),
    ]
